//This file was autogenerated by autoreq with the following parameters:
//___________
//fileName   : *.js
//basePath   : .
//output     : app\polyfills\requireme.ts
//inputs     : app\polyfills
//Ignored app/polyfills/requireme because its file name matches with the output file
