//This file was autogenerated by autoreq with the following parameters:
//cd         : c:\Users\rafael\Documents\Web\app
//___________
//fileName   : *.js
//basePath   : .
//output     : app\polyfills\requireme.ts
//inputs     : app\polyfills
import 'app/polyfills/functionName';
//Ignored app/polyfills/requireme because its file name matches with the output file
