//This file was autogenerated by autoreq with the following parameters:
//cd         : c:\Users\rafael\Documents\Web\app
//___________
//fileName   : requireme.ts
//basePath   : app
//output     : app\main\requireme.ts
//inputs     : app
import 'features\login\requireme';
//Ignored main\requireme because its file name matches with the output file
import 'polyfills\requireme';
