//This file was autogenerated by autoreq with the following parameters:
//cd         : c:\Users\rafael\Documents\Repos\Contabilidad\AngularTypescriptSkeleton
//___________
//fileName   : requireme.ts
//basePath   : .
//output     : app\main\requireme.ts
//inputs     : app
import 'app/features/home/requireme';
import 'app/features/login/requireme';
//Ignored app/main/requireme because its file name matches with the output file
import 'app/polyfills/requireme';
